config/routes.rb
Rails.application.routes.draw do
  resources :contact_infos

  match 'contact_infos/searchContacts' => 'contact_infos#searchContacts', via: [:post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
    validates_presence_of :name, :address

    def as_json(options={})
        super(:only => [:id, :name, :address])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
    def index
        @contacts = ContactInfo.all
    end

    def searchContacts
        @searchedContacts = ContactInfo.where([' name LIKE? ',"%#{params[:phrase]}%"])
                                        .select(:id, :name, :address, :mobile, :email)
        render :json => @searchedContacts.as_json(:only => [:id, :name, :address, :mobile, :email])
    end

    def new
        @contact = ContactInfo.new
    end

    def edit
        @contact = ContactInfo.find(params[:id])
    end

    def create
        @contact = ContactInfo.new(contact_params)
        if @contact.save
            redirect_to contact_infos_path, :notice => 'Your contact was created successfully'
        else
            render 'new'
        end
    end

    def update
        @contact = ContactInfo.find(params[:id])
        if @contact.update_attributes(contact_params)
            redirect_to contact_infos_path, :notice => 'Your contact was updated successfully'
        else
            render 'edit'
        end
    end

    def destroy
        @contact = ContactInfo.find(params[:id])
        @contact.destroy
    end

    def show
        @contact = ContactInfo.find(params[:id])
    end

    def contact_params
        params.require(:contact_info).permit(:name, :address, :phone, :mobile, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/views/contact_infos/_form.html.erb
<div class = "col-sm-8 col-sm-offset-2">
<% if @contact.errors.any? %>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <%= pluralize(@contact.errors.count, "error") %> occured.
        </div>
        <div class="panel-body">
            <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

    <%= form_for @contact, :class => 'form-horizontal' do |f| %>
       <div class="form-group custom-form">
            <%= f.label :name, :class => 'control-label col-sm-2' %>
           <div class="col-sm-10">
                <%= f.text_field :name, :class => 'form-control' %>
           </div>
       </div>

       <div class="form-group custom-form">
            <%= f.label :address, :class => 'control-label col-sm-2' %>
           <div class="col-sm-10">
                <%= f.text_field :address, :class => 'form-control'%>
           </div>
       </div>

       <div class="form-group custom-form">
            <%= f.label :mobile, :class => 'control-label col-sm-2' %>
           <div class="col-sm-10">
                <%= f.text_field :mobile, :class => 'form-control'%>
           </div>
       </div>

       <div class="form-group custom-form">
            <%= f.label :email, :class => 'control-label col-sm-2' %>
           <div class="col-sm-10">
                <%= f.text_field :email, :class => 'form-control'%>
           </div>
       </div>

       <div class="form-group custom-form">
            <%= f.label :phone, :class => 'control-label col-sm-2' %>
           <div class="col-sm-10">
                <%= f.text_field :phone, :class => 'form-control'%>
           </div>
       </div>

       <div class="form-group custom-form">
            <div class="col-sm-2 col-sm-offset-2">
                <%= f.submit "Save", :class => 'btn btn-info' %>
            </div>
       </div>          
                
    <% end %>
</div>

app/views/contact_infos/edit.html.erb
<%= render 'form' %>

app/views/contact_infos/index.html.erb
<div class = "row">
        <div class="col-md-3 col-sm-12">
                <div class="form-group">
                    <input type = "text" 
                                placeholder = "Search Contacts" 
                                id="square"
                                class="form-control"ß/>
                </div>
        </div>
        <div class = "col-md-9 col-sm-12">
            <table class = "table table-condensed">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th class="hidden-xs">Phone</th>
                                <th>Mobile</th>
                                <th class="hidden-xs">Email</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id = "contacts">
                            <% @contacts.each do |contact| %>
                                <tr>
                                    <td><%= link_to(contact.name, contact_info_path(contact) ) %></td>
                                    <td><%= contact.address%></td>
                                    <td class="hidden-xs"><%= contact.phone%></td>
                                    <td><%= contact.mobile%></td>
                                    <td class="hidden-xs"><%= contact.email%></td>
                                    <td>
                                        <div class="btn-group" role="group">
                                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                                Actions
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <%= link_to('Delete '+contact.name,'#',  
                                                        :class => 'askConfirmation',
                                                        :value => contact.id) 
                                                    %>
                                                </li>
                                                <li>
                                                    <%= link_to('Edit '+ contact.name, 
                                                    edit_contact_info_path(contact),
                                                    :method => :get) %>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
            </table>
        </div>
</div>

app/views/contact_infos/new.html.erb
<%= render 'form' %>

app/views/contact_infos/show.html.erb
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                Name: <%= @contact.name %>
            </div>
            <div class="panel-body">
                Address: <%= @contact.address %>
            </div>
            <div class="panel-footer">
                <button type="button" 
                        class="btn btn-success btn-md">
                            <%= @contact.mobile %>
                            <i class="fa fa-phone"></i>
                </button>
                <button type="button" 
                        class="btn btn-success btn-md">
                            <%= @contact.email %>
                            <i class="fa fa-envelope-open"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="col-md-5 col-md-offset-2">
        <div id="map">My Location</div>
    </div>
</div>
<script>
  $(document).ready(function(){
    var map = new GMaps({
      div: '#map',
      lat: -12.043333,
      lng: -77.028333,
      height: '500px',
      width: '500px'
    });

    GMaps.geocode({
        address: '<%= @contact.address %>',
        callback: function(results, status) {
            if (status == 'OK') {
            var latlng = results[0].geometry.location;
            map.setCenter(latlng.lat(), latlng.lng());
            map.addMarker({
                lat: latlng.lat(),
                lng: latlng.lng()
            });
            }
        }
    });

  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src = 'http://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>'></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
       <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to('Home', contact_infos_path, :class => 'navbar-brand') %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('New',new_contact_info_path, :class => 'fa fa-plus') %></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
        </div>
    </nav>
    <% if flash.any?%>
      <% flash.each do |type, message| %>
        <script>
          toastr.options = {
            "positionClass":"toast-bottom-right"
          }
          toastr.info('<%= message %>');
        </script>
      <% end %>
    <% end %>
    <div class="container-fluid">
            <%= yield %>
    </div>
    
  </body>
</html>